name: Dashboard Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up and install dependencies
        run: |
             sudo apt install python3.10-venv
             python -m venv --copies antenv
             source antenv/bin/activate
             pip install setuptools
             pip install -r requirements.txt


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: sales-dashboard
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
          startup-command: python app.py
